title: '<a href="https://www.filamentgroup.com" class="project-logo">Filament Group</a> <span>carousel</span>'
description: An accessible carousel web component
theme: jekyll-theme-cayman
show_downloads: true
